### ISSUE TITLE
Unable to build the agent.

### ISSUE THREAD

**Issue by rohansuri1996** [multiverse-nms/ndn-dpdk-agent#13]
Hi,

I was trying to build the ndndpdk agent and followed all the steps in the description but I am getting an error which I am unable to figure out. I was able to build the container but when I ran it (sudo docker run -it --rm --name my-agent --network="host" -v /home/praktikant/rohan/ndn-dpdk/my-agent:/opt/data ndn-dpdk-agent). It threw me this error-

> java.nio.file.FileSystemNotFoundException
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
> 	at java.nio.file.Paths.get(Paths.java:143)
> 	at nms.MainVerticle.getConfigRetriever(MainVerticle.java:118)
> 	at nms.MainVerticle.start(MainVerticle.java:59)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:745)
> 12:00:17.464 [vert.x-eventloop-thread-1] ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle
> java.nio.file.FileSystemNotFoundException: null
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
> 	at java.nio.file.Paths.get(Paths.java:143)
> 	at nms.MainVerticle.getConfigRetriever(MainVerticle.java:118)
> 	at nms.MainVerticle.start(MainVerticle.java:59)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:745)
> java.nio.file.FileSystemNotFoundException
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
> 	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
> 	at java.nio.file.Paths.get(Paths.java:143)
> 	at nms.MainVerticle.getConfigRetriever(MainVerticle.java:118)
> 	at nms.MainVerticle.start(MainVerticle.java:59)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by amar-ox** [comment]
Make sure you followed instructions to run the controller. 
Then check your docker volume (path and config.json file)
Also, the ndn-dpdk forwarder should be running when the agent starts.
